### ISSUE TITLE
No conncetion to ETS5

### ISSUE THREAD

**Issue by DrAColian** [calimero-project/calimero-testnetwork#4]
Hey,

I've setup the calimero-testnetwork on docker to have a development system running so I can play around with my development Edomi setup.

Unfortunately, it doesn't seem to work and I have no idea, what might be wrong.

So, I tried to connect to the testnetwork with ETS5, but the interface cannot be established. "connection type not supported. Contact your vendor."

What am I doing wrong or missing?

EDIT:
So, this ist, what the docker container log says:
> 16:37:35:751 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:54740: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address X, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
> 16:37:35:830 INFO io.calimero.server.test-server - accepted test-server KnxTestNetwork tcp connection 192.168.20.10:58543
> 16:37:35:830 WARN io.calimero.server.test-server - reject KNXnet/IP connect.req (0x205 v1.0) length 26, secure services required for tunneling
> 16:37:35:830 WARN io.calimero.server.test-server - no data endpoint for remote endpoint /192.168.20.10:58543, the requested connection type is not supported
> 16:37:35:856 INFO io.calimero.server.test-server - close tcp connection to 192.168.20.10:58543
> 16:37:36:297 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:61033: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address X, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
> 16:37:36:770 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:61034: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address X, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
> 16:37:37:140 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:61036: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address X, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020

Seems, that the server closes the connection because of missing secure services?!

EDIT 2:
I activated the "Secured" checkbox on the interface which resulted in the following:
> 17:54:05:311 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:63588: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address X, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
> 17:54:05:323 INFO io.calimero.server.test-server - accepted test-server KnxTestNetwork tcp connection 192.168.20.10:49802
> 17:54:05:337 ERROR io.calimero.server.knxnetip.KnxTestNetwork.KNX IP 🔒 Session - error processing KNXnet/IP session.req (0x951 v1.0) length 46, error creating secure session keys for 192.168.20.10:49802

Still no connection, but one step further. :)

Kind regards
Dr.A.Colian

**Comment by bmalinowsky** [comment]
Hey, 
the reason is that the test-network starts up with a keyfile to enable knx secure services. As your ETS doesn't know those keys, it won't be able to connect. The config you have in your docker image is a little outdated and doesn't configure secure services optional anymore.

So you can either empty the keyfile entries in _/usr/app/keyfile_ (so that there is an empty file), or you can re-pull the docker image. I pushed a new one where the use of secured services should be optional.

**Comment by DrAColian** [comment]
Hey @bmalinowsky,
thanks for your reply. I just realised, that this is the way. I changed the server-config and removed the keyfile part in the servicecontainer, which did the job as well.

ETS connects now, Great!

Next, I tried to connect with edomi, but it looses the connection every 10 seconds or so. This is quite annoying, as it spams the error log and communication is not really possible.

Not sure, if it has something to do with this behaviour of the server:
> 17:42:07:344 INFO io.calimero.server.calimero-test-server - enable IP system broadcast routing mode
> 17:42:13:330 INFO io.calimero.server.calimero-test-server - disable IP system broadcast routing mode
> 17:42:23:351 INFO io.calimero.server.calimero-test-server - enable IP system broadcast routing mode
> 17:42:29:337 INFO io.calimero.server.calimero-test-server - disable IP system broadcast routing mode

And then the devices add a lot of traffic to the KNX net. So, it's not really the best testing environment, but I cannot get the docker calimero-server running - even when using the same server-config from the testnetwork. Dunno, that I'm doing wrong.

**Comment by bmalinowsky** [comment]
The enable/disable IP ... log messages are unrelated. That the devices generate knx traffic is the main point of the test-network setup.

What's the exact problem with starting the calimero-server?

**Comment by DrAColian** [comment]
Well, the container with the server starts, but there is no way I can establish a connection with ETS - which is strange, as I use the docker container with the exact same config as the test-network. So, I start the container, and try to connect with ETS5, which gives me the following log entries:

For calimero-testnetwork - started via portainer:
`21:18:28:014 INFO io.calimero.server.test-server - Calimero KNX IP server v3.0-SNAPSHOT
21:18:57:051 INFO io.calimero.server.test-server - close tcp connection to 192.168.20.10:56754
service container KnxTestNetwork:
21:18:28:028 INFO io.calimero.server.test-server - use configuration 'KNX test network (Docker)' with 1 service container, discovery: listen on [all] send on [all] interfaces
	listen on any (port 3671), KNX IP routing multicast group 224.0.23.12
	virtual KnxTestNetwork connection: TP1 medium, device 1.1.0
	Group address filter [1/0/1, 1/0/2, 1/0/3, 1/0/4, 1/0/5, 1/0/6, 1/0/7, 1/0/11, 1/0/111]
21:18:28:047 INFO io.calimero.server.gateway.test-server - activate 'KnxTestNetwork' disruption buffer on ports [5,555-5,559], disruption timeout 30 s
21:18:28:084 INFO io.calimero.server.test-server - test-server discovery endpoint [eth0, lo] is up and running
21:18:28:087 INFO io.calimero.knxnetip.KNXnet/IP Routing 224.0.23.12:3671 - multicast loopback mode enabled
21:18:28:099 INFO io.calimero.server.test-server - test-server KnxTestNetwork tcp service (eth0 172.17.0.3:3671) is up and running
21:18:28:088 INFO io.calimero.server.test-server - test-server KnxTestNetwork KNX IP routing service (0.0.0.0 224.0.23.12) is up and running
21:18:28:089 INFO io.calimero.server.test-server - KnxTestNetwork secure mgmt/tunneling connections: optional/optional
21:18:28:099 INFO io.calimero.server.test-server - test-server KnxTestNetwork control endpoint (eth0 172.17.0.3:3671) is up and running
Test network is up and running
21:18:56:948 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:60216: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address 02:42:ac:11:00:03, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
21:18:56:957 INFO io.calimero.server.test-server - accepted test-server KnxTestNetwork tcp connection 192.168.20.10:56753
21:18:56:958 INFO io.calimero.server.test-server - KnxTestNetwork: setup data endpoint (channel 1) for connection request from 192.168.20.10:56753 (tcp)
21:18:56:964 INFO io.calimero.server.test-server - test-server KnxTestNetwork data endpoint KNX IP LinkLayer 192.168.20.10:56753 (channel 1, 1.1.10) is up and running
21:18:56:959 INFO io.calimero.server.test-server - assign additional individual address 1.1.10 to channel 1
21:18:56:992 INFO io.calimero.server.test-server - KnxTestNetwork data endpoint 192.168.20.10:56753 closed
21:18:56:997 INFO io.calimero.server.test-server - close tcp connection to 192.168.20.10:56753
21:18:57:001 INFO io.calimero.server.test-server - send KNXnet/IP description to /192.168.20.10:54434: "KNX test network (Docker)", KNX address 1.1.0, KNX medium TP1, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address 02:42:ac:11:00:03, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
21:18:57:009 INFO io.calimero.server.test-server - accepted test-server KnxTestNetwork tcp connection 192.168.20.10:56754
21:18:57:011 INFO io.calimero.server.test-server - KnxTestNetwork: setup data endpoint (channel 2) for connection request from 192.168.20.10:56754 (tcp)
21:18:57:011 INFO io.calimero.server.test-server - assign additional individual address 1.1.10 to channel 2
21:18:57:011 INFO io.calimero.server.test-server - test-server KnxTestNetwork data endpoint KNX IP LinkLayer 192.168.20.10:56754 (channel 2, 1.1.10) is up and running
21:18:57:045 INFO io.calimero.server.test-server - KnxTestNetwork data endpoint 192.168.20.10:56754 closed`

ETS5 says, the interface connect test is ok.

For the calimero-server docker: I start the container from shell with the following command:
`docker run --rm -ti --net bridge -p 3671:3671/udp -p 3671:3671 -v /calimero-server/config/server-config.xml:/usr/app/server-config.xml calimeroproject/knxserver server-config.xml`

and here is the log output:
`WARNING: Unknown module: io.calimero.serial.provider.rxtx specified to --add-reads
21:13:03.770 [INFO   ] io.calimero.server.calimero-test-server: Calimero KNX IP server v3.0-SNAPSHOT
21:13:03.784 [INFO   ] io.calimero.server.calimero-test-server: use configuration 'KNX test network (Docker)' with 1 service container, discovery: listen on [all] send on [all] interfaces
service container KnxTestNetwork:
	listen on any (port 3671), KNX IP routing multicast group 224.0.23.12
	virtual KnxTestNetwork connection: KNX IP medium, device 1.1.0
21:13:03.792 [INFO   ] io.calimero.server.gateway.calimero-test-server: activate 'KnxTestNetwork' disruption buffer on ports [5,000-5,559], disruption timeout 30 s type 'stop' to stop the gateway and shutdown the server
21:13:03.820 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server discovery endpoint [eth0, lo] is up and running
21:13:03.829 [INFO   ] io.calimero.server.calimero-test-server: KnxTestNetwork secure mgmt/tunneling connections: optional/optional
21:13:03.833 [INFO   ] io.calimero.knxnetip.KNXnet/IP Routing 224.0.23.12:3671: multicast loopback mode enabled
21:13:03.835 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork KNX IP routing service (0.0.0.0 224.0.23.12) is up and running
21:13:03.836 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork control endpoint (eth0 172.17.0.3:3671) is up and running
21:13:03.837 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork tcp service (eth0 172.17.0.3:3671) is up and running
21:13:34.274 [INFO   ] io.calimero.server.calimero-test-server: send KNXnet/IP description to /192.168.20.10:60249: "KNX test network (Docker)", KNX address 1.1.0, KNX medium KNX IP, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address 02:42:ac:11:00:03, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
21:13:34.286 [INFO   ] io.calimero.server.calimero-test-server: accepted calimero-test-server KnxTestNetwork tcp connection 192.168.20.10:56219
21:13:34.287 [INFO   ] io.calimero.server.calimero-test-server: KnxTestNetwork: setup data endpoint (channel 1) for connection request from 192.168.20.10:56219 (tcp)
21:13:34.290 [INFO   ] io.calimero.server.calimero-test-server: assign additional individual address 1.1.10 to channel 1
21:13:34.298 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork data endpoint KNX IP LinkLayer 192.168.20.10:56219 (channel 1, 1.1.10) is up and running
21:13:34.323 [INFO   ] io.calimero.server.calimero-test-server: KnxTestNetwork data endpoint 192.168.20.10:56219 closed
21:13:34.328 [INFO   ] io.calimero.server.calimero-test-server: close tcp connection to 192.168.20.10:56219`

Although it seems, there is a connection, ETS5 gives the warning, that the interface cannot be found.

Not sure, what I'm doing wrong here - as I thought it should work...

Thanks for taking your time and getting back to me.

**Comment by bmalinowsky** [comment]
AFAIK, the default docker bridge is set up for communication between containers, not to other hosts. What if you start the container with `--net host`?

**Comment by DrAColian** [comment]
It's true, that the bridge is primarily for docker internal communication, but you can expose ports, so you can connect to the container from home network via the docker host. This is the same with the knxtestnetwork - and it works.

But even, if I use macvlan driver (which allows the container to be in my home network), the result is the same: 
> rancher@docker-hub:/calimero-server/config$ docker run --rm -ti --net smarthome_net -v /calimero-server/config/server-config.xml:/usr/app/server-config.xml calimeroproject/knxserver server-config.xml
WARNING: Unknown module: io.calimero.serial.provider.rxtx specified to --add-reads
> 16:44:46.056 [INFO   ] io.calimero.server.calimero-test-server: Calimero KNX IP server v3.0-SNAPSHOT
> 16:44:46.068 [INFO   ] io.calimero.server.calimero-test-server: use configuration 'KNX test network (D0ck3r)' with 1 service container, discovery: listen on [all] send on [all] interfaces
service container KnxTestNetwork:
        listen on any (port 3671), KNX IP routing multicast group 224.0.23.12
        virtual KnxTestNetwork connection: KNX IP medium, device 1.1.0
> 16:44:46.077 [INFO   ] io.calimero.server.gateway.calimero-test-server: activate 'KnxTestNetwork' disruption buffer on ports [5,000-5,559], disruption timeout 30 s
type 'stop' to stop the gateway and shutdown the server
> 16:44:46.108 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server discovery endpoint [eth0, lo] is up and running
> 16:44:46.113 [INFO   ] io.calimero.knxnetip.KNXnet/IP Routing 224.0.23.12:3671: multicast loopback mode enabled
> 16:44:46.115 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork KNX IP routing service (0.0.0.0 224.0.23.12) is up and running
> 16:44:46.122 [INFO   ] io.calimero.server.calimero-test-server: KnxTestNetwork secure mgmt/tunneling connections: optional/optional
> 16:44:46.131 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork tcp service (eth0 192.168.11.2:3671) is up and running
> 16:44:46.131 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork control endpoint (eth0 192.168.11.2:3671) is up and running
> 16:46:55.312 [INFO   ] io.calimero.server.calimero-test-server: send KNXnet/IP description to /192.168.20.10:63080: "KNX test network (D0ck3r)", KNX address 1.1.0, KNX medium KNX IP, Installation 0 - Project 0 (ID 0), KNX IP multicast address 224.0.23.12, MAC address 02:42:c0:a8:0b:02, S/N 0000:00000000, Core (v2), Device Management (v2), Tunneling (v2), Routing (v2), 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.1.19, 1.1.20, 1.1.21, 1.1.22, 1.1.23, 1.1.24, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.29, 1.1.30, KNX manufacturer ID 0x0, data 0x626d323031312020
> 16:46:55.331 [INFO   ] io.calimero.server.calimero-test-server: accepted calimero-test-server KnxTestNetwork tcp connection 192.168.20.10:64610
> 16:46:55.332 [INFO   ] io.calimero.server.calimero-test-server: KnxTestNetwork: setup data endpoint (channel 1) for connection request from 192.168.20.10:64610 (tcp)
> 16:46:55.336 [INFO   ] io.calimero.server.calimero-test-server: assign additional individual address 1.1.10 to channel 1
> 16:46:55.345 [INFO   ] io.calimero.server.calimero-test-server: calimero-test-server KnxTestNetwork data endpoint KNX IP LinkLayer 192.168.20.10:64610 (channel 1, 1.1.10) is up and running
> 16:46:55.392 [INFO   ] io.calimero.server.calimero-test-server: KnxTestNetwork data endpoint 192.168.20.10:64610 closed
> 16:46:55.398 [INFO   ] io.calimero.server.calimero-test-server: close tcp connection to 192.168.20.10:64610

As you can see, the container IP is 192.168... but still the connection is closed and ETS moans "interface not found".

**Comment by bmalinowsky** [comment]
True, I didn't think about the -p args. 
What I notice with your `--net host` setup is that your netmask part is still different, but ok.

So, I tried the same bridge setup, running docker on linux and checked with ETS 6, 
`docker run -it --rm --net bridge -p 3671:3671/udp -p 3671:3671/tcp -v $(pwd)/src/main/resources/server-config.xml:/usr/app/server-config.xml calimeroproject/knxserver -vvv server-config.xml`

* ETS automatic discovery doesn't work, which is ok when using the bridge
* when configuring the connection in ETS, I have to use NAT, which is expected
* when using a calimero virtual config, ETS tells me that the knx bus is not connected (expected), you can change the config to use `knxSubnet type="emulate"` to avoid that
* BUT: opening group monitor does work, ETS is using tcp (expected)
    * when using a "virtual" setup write/read won't do anything (because the virtual setup doesn't have any devices added)
    * using the "emulate" setup, I can do process communication

Maybe, just maybe, the "interface not found" in ETS 5 is that you use the virtual setup?

**Comment by DrAColian** [comment]
Thanks for your further testing - but I don't have any problem connecting with ETS5 to the knxtestnetwork, only to the server.

Here is a screenshot of my first test: knxestnetwork with bridge
![2024-01-09 17_54_45-ETS5™](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/2cc3eb9e-d900-4414-869d-10a36eb017b4)

As you can see, the container is up and running on bridge, and the forwarded port allows a connection through the ETS5 interface menu.

Just for testing, I used the macvlan driver, which changes the IP of the container, but allows the same connection:
![2024-01-09 17_51_53-Portainer _ local](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/0d021707-00e1-44f7-9f19-5473ba92bad0)

But if I do the same with the docker container for calimero-server, the "testing" through the interface menu is not possible:
![2024-01-09 18_01_12-ETS5™](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/22b05118-a47c-4dd6-8a9c-5cc393bae428)

As you said, groupmonitor is working, but ETS is loosing the connection the knxserver every few seconds - the latter does not happen for knxtestnetwork: (The loss of conncection also is a problem for Edomi in both situations.)
![2024-01-09 18_13_49-Greenshot](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/a24f0bc8-baf1-43f0-a56a-34d4dbd01d68)

Sending commands to the bus also works.

Here is the server-config I used for both containers:
![2024-01-09 17_48_19-rancher@docker-hub_ ~](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/fda2887e-6e63-4878-81a6-9dd9aaa10710)

So, something IS different between (the docker containers of) knxtestnetwork and knxserver, but I'm not sure, what it could be.

**Comment by bmalinowsky** [comment]
> But if I do the same with the docker container for calimero-server

In the picture I think the ETS message is just misleading, because it obviously finds the server. The "error" I get is that the "The interface can be connected from the PC, but is not connected to the KNX bus", which is at least technically correct, as the virtual network does indeed state it is not connected to a "knx bus" in the beginning.

If I look at your last picture from the portainer and ETS the following message with status 00 and 01

> send tunneling-feat.info connection status 00

timestamps 17:11:17 or 18:11:37 in ETS, 
the Verbindungsereignis corresponds to that, which is generated by the server to indicate that the "knx bus" (which doesn't exist) is connected or not. Not the IP connection itself. And after sending 1.1.10->1/1/1 to the subnet, it is set to connected again (which is what the implementation does).

All the `tunneling-feat.info connection status 0x` are the knx bus, not the client connection. I don't know why it get's disconnected before though. 

The difference what the config makes is the following: in the testnetwork the virtual network is populated with 2 test devices which actually generate traffic (which set the network to connected).
If you use the same config for the knxserver, the virtual network stays empty.


> If I use "emulate" as subnet type, the server won't send a "connection acknowledged".

Can you add a trace or picture of that so I can see what leads to that?

**Comment by DrAColian** [comment]
Hey @bmalinowsky,

sorry, it took some time to answer, but it have been some busy days.

So, here are some screenshots of what happens.
This is the log of calimero server with "emulate" as subnet type:
![2024-01-13 23_37_23-Portainer _ local](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/88fa317e-cdd2-4c3c-8f03-77f403a25d4f)

And the corresponding log of EDOMI:
![2024-01-13 23_37_47-devedomi_data_log_ERRLOG_2024-01 htm_20240113233702](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/d8f61774-e118-44c1-91f4-0e36235314fd)

Interestingly, this is the log, when I try to connect with ETS5 (which seems to work):
![2024-01-13 23_47_39-Portainer _ local](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/321d71b0-4f24-4813-bac2-db886a1c2cd1)

In comparison, the logs of calimero server and EDOMI when using "virtual" as a subnet:
![2024-01-13 23_40_54-Portainer _ local](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/faa31cae-f88d-4fb4-be45-b591b644c3d4)

![2024-01-13 23_41_36-devedomi_data_log_ERRLOG_2024-01 htm_20240113234023](https://github.com/calimero-project/calimero-testnetwork/assets/44818206/591383fc-c074-41a9-971f-b8df193cb417)

I guess, as ETS5 works, there is no need for you to change anything, but maybe you have an idea, what makes the difference between ETS and EDOMI?!

Kind regards

**Comment by bmalinowsky** [comment]
Hello @DrAColian ,

I did now more tests with various setups and found some other bugs in the ETS, but that shouldn't be the issue here. Anyway, the difference between EDOMI and ETS is that EDOMI uses UDP, while ETS uses TCP. So one cannot directly compare the output.

Regarding the first 2 pics: one log shows UTC time, the other adjusted (+1), but there should be a correlation in the minute (minute 37) which I cannot see. Any tunneling request should show in the server log at approx. the same timestamp (-1 hour). There is none.

Regarding the E_KNX_CONNECTION ("Verbindung zum Bus"). I changed the server virtual setup to immediately show the subnet as connected which is totally fine and will improve log/warning/error stuff. In my ETS 6 this removes the warning on connecting, so I'm quite you will see a difference for the better. I pushed a new docker image with the patch. At least the EDOMI connection-state "Verbindung verloren" should vanish.

Maybe you can give it a try.

**Comment by DrAColian** [comment]
Hi @bmalinowsky,

thanks for the new docker image. I tried it, but now, EDOMI shows the same error on virtual as on emulate: "No TUNNELING_ACK from router".

Strange.

**Comment by bmalinowsky** [comment]
I think I made progress wrt UDP and the issue when using the docker bridge. The bridge requires a NAT connection, all nice and fine, but there are basically 2 different variants:

- source NAT
- destination NAT

Source NATting works fine, but the thing is that bridging needs both, i.e., also destination NAT. The server sends back its (from its own network viewpoint) data endpoint, but that endpoint won't be reachable anymore once it is used by the client. The datapoint isn't reachable over the network because the port isn't published, and since the port assignments are dynamic, it cannot easily be done statically during startup of the container.

(You can test that behavior with the current server image if you use  `udpOnly="true"` as attribute in the `<serviceContainer ...` XML element. ETS then experiences the same problem as EDOMI does.) 

So I added a workaround for this, and pushed a new image. When using UDP connections, the former image fails after establishing the connection because the destination can't be reached anymore. The new image uses the published port (3671) also for data connections and internally forwards it.

**Comment by DrAColian** [comment]
Hey @bmalinowsky 
haven't tried the latest image yet, just had the previous one running for some days now, and there has been no issue. Thank's alot, it's really running great.

I have a question regarding some config of knxserver, but I will ask that in the corresponding git.
